In [15]:
import numpy as np
import pandas as pd

In [2]:
from pandas import Series, DataFrame

# pandas 자료구조

In [3]:
#1. Series: 일련의 객체를 담을 수 있는 1차원 배열같은 자료구조

obj=pd.Series([4,7,-5,3]) #가장 간단한 Series객체는 배열 데이터로부터 생성가능
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
print(obj.index, obj.values)

RangeIndex(start=0, stop=4, step=1) [ 4  7 -5  3]


In [6]:
obj2=pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
print(obj2.index, obj2.values)

Index(['d', 'b', 'a', 'c'], dtype='object') [ 4  7 -5  3]


In [10]:
obj2[['d','a','c']]

d    4
a   -5
c    3
dtype: int64

In [11]:
obj2[obj2>3]

d    4
b    7
dtype: int64

In [12]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
#Series는 고정 길이의 정렬된 사전형이라고 생각하자
'b' in obj2

True

In [18]:
data={'Ohio':35000,'Texas':7100,'Oregon':16000,'Utah':5000}
obj3=pd.Series(data) #파이썬 사전 객체로부터 Series 객체 생성
obj3

Ohio      35000
Texas      7100
Oregon    16000
Utah       5000
dtype: int64

In [19]:
states=['California','Ohio','Texas']
obj4=pd.Series(data,index=states) #색인 직접 넘겨주기
obj4

California        NaN
Ohio          35000.0
Texas          7100.0
dtype: float64

In [20]:
pd.isnull(obj4) #누락한 데이터 찾기 :isnull, notnull

California     True
Ohio          False
Texas         False
dtype: bool

In [22]:
pd.notnull(obj4)

California    False
Ohio           True
Texas          True
dtype: bool

In [26]:
obj3+obj4 #산술연산에서 색인과 라벨로 자동정렬

California        NaN
Ohio          70000.0
Oregon            NaN
Texas         14200.0
Utah              NaN
dtype: float64

In [24]:
obj4.name ='population' #name속성
obj4.index.name='state'
obj4

state
California        NaN
Ohio          35000.0
Texas          7100.0
Name: population, dtype: float64

In [25]:
obj.index=['Bob','Steve','Jeff','Ryan'] #Series의 색인은 대입하여 변경가능
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [27]:
#2. DataFrame: 표 같은 스프레드시트 형식의 자료구조, Series객체를 담고 있는 파이썬 사전으로 생각하자

data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
     'year':[2000,2001,2002,2001,2002,2003],
     'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [28]:
frame.head() #상위5개 추출

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [29]:
pd.DataFrame(data,columns=['year','state','pop']) #column순서 지정

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [30]:
frame2=pd.DataFrame(data, columns=['year','state','pop','debt'],
                   index=['one','two','three','four','five','six']) #사전에 없는 값을 넘기면 결측치로 저장
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [31]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [32]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [33]:
frame2.loc['three'] #로우는 위치나 loc속성을 이용하여 이름을 통해 접근 가능

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [36]:
frame2['debt']=np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [37]:
val=pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])
frame2['debt']=val #Series를 대입하면 DataFrame의 색인에 따라 값이 대입, 존재하지 않는 색인은 결측치
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

# 

In [42]:
frame2['eastern'] = (frame2.state=='Ohio') #존재하지 않는 컬럼을 대입하면 새로운 컬럼 생성
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [43]:
del frame2['eastern'] #del예약어로 컬럼 삭제
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [44]:
#caution: DataFrame의 색인을 이용하여 얻은 컬럼은 copy가 아닌 view임.

In [48]:
pop={'Ohio':{2000:1.5,2001:1.7,2002:3.6},
     'Nevada':{2001: 2.4, 2002:2.9} }
frame3=pd.DataFrame(pop) #중첩된 사전을 이용하여 데이터를 생성하면 바깥에 있는 사전의 키는 컬럼, 안에 있는 키는 로우
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [49]:
frame3.T #데이터를 전치

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [50]:
pdata={'Ohio':frame3['Ohio'][:-1],
      'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [52]:
frame3.index.name='year'; frame3.columns.name='state' #name속성
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [53]:
frame3.values #2차원 배열로 반환

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [54]:
#3. 색인객체: 표 형식의 데이터에서 각 로우나 컬럼에 대한 이름과 메타데이터를 저장하는 객체

obj =pd.Series(range(3),index=['a','b','c']) #객체를 생성할 때 사용되는 배열은 내부적으로 색인으로 변환
index=obj.index 
index

Index(['a', 'b', 'c'], dtype='object')

In [56]:
#index[1]='d' 색인객체는 변경 불가능

In [57]:
labels =pd.Index(np.arange(3))
obj2=pd.Series([1.5,2.5,0], index=labels)
obj2

0    1.5
1    2.5
2    0.0
dtype: float64

In [58]:
obj2.index is labels

True

In [59]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [60]:
frame3.columns #Index객체는 고정 크기로 동작

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [62]:
'Ohio' in frame3.columns

True

In [63]:
dup_labels=pd.Index(['foo','foo','bar','bar']) #파이썬 집합과 달리 pandas 인덱스는 중복되는 값을 허용
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 핵심 기능

In [64]:
#1. reindex(재색인): 새로운 색인에 맞도록 객체를 새로 생성
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [66]:
obj2=obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [72]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [75]:
obj3.reindex(range(6),method='ffill') #순차적인 데이터를 재색인할 때 값을 보관해야할 경우: method옵션
#누락된 값을 직전의 값으로 채우기: ffill메서드

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [76]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
                  index=['a','c','d'],
                  columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [79]:
frame2=frame.reindex(['a','b','c','d']) #DataFrame에 대한 reindex는 로우, 컬럼 둘 다 변경 가능
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [81]:
state2=['Texas','Utah','California']
frame2.reindex(columns=states) #컬럼에 대한 reindex는 columns 예약어를 통해 가능

California  Ohio  Texas
a         2.0   0.0    1.0
b         NaN   NaN    NaN
c         5.0   3.0    4.0
d         8.0   6.0    7.0

In [85]:
frame2.loc[['a','b','c','d'],states] #loc을 통해 라벨로 색인하면 더 간결하게 가능

California  Ohio  Texas
a         2.0   0.0    1.0
b         NaN   NaN    NaN
c         5.0   3.0    4.0
d         8.0   6.0    7.0

In [87]:
#2. 하나의 로우나 컬럼 삭제하기

obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [88]:
new_obj=obj.drop('c') #drop메서드로 선택한 값들이 삭제된 새로운 객체를 얻을 수 있음
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [91]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [92]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
data.drop('two',axis=1) #DataFrame의 column을 삭제할 때 axis=1이나 axos=columns를 넘겨주기

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [94]:
obj.drop('c',inplace=True) #Series나 DataFrame의 크기 또는 형태를 변경하는 함수는 새로운 객체를 반환하는 대신 원본 객체 변경
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [95]:
#3. 색인, 선택, 거르기

obj=pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [96]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [97]:
obj[['b','a','d']]#Series의 색인은 정수가 아니어도 됨

b    1.0
a    0.0
d    3.0
dtype: float64

In [98]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [101]:
obj['b':'c']=5 #일반 파이썬의 슬라이싱과 다르게 라벨이름으로 슬라이싱하면 끝점까지 포함
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [103]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data[['three','four']] #DataFrame에서 하나 이상의 컬럼 값을 가져올 수 있음

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [107]:
data['Ohio':'Utah']

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [109]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [110]:
data<5 #스칼라 비교를 통해 생성된 불리언 DataFrame을 사용하여 값 선택

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [111]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [112]:
data.loc['Colorado',['two','three']] #축이름을 선택할 때는 loc을, 정수 색인으로 선택할 때는 iloc을 사용

two      5
three    6
Name: Colorado, dtype: int32

In [113]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [114]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [115]:
data.loc[:'Utah','two'] #단일 라벨이나 라벨 리스트도 지원

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [116]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [120]:
#4. 정수색인: 라벨 색인이 0,1,2를 포함하는 경우? 사용자가 라벨 색인 선택 혹은 정수 색인 선택인지 추측하기 어려움

ser2=pd.Series(np.arange(3.),index=['a','b','c']) #정수 기반의 색인을 사용하지 않으면 됨
ser2[-1] 

2.0

In [121]:
ser[:1]

0    0.0
dtype: float64

In [122]:
#5. 산술 연산과 데이터 정렬

s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])
s1+s2 #다른 색인을 가지고 있는 객체들이라면 결과에 두 색인이 통합되며, 서로 겹치는 색인이 없으면 NaN값

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [125]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
df1+df2 #DataFrame의 경우 정렬은 로우와 컬럼 모두에 적용

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [126]:
df1=pd.DataFrame({'A':[1,2]})
df1

A
0  1
1  2

In [128]:
df2=pd.DataFrame({'B':[3,4]})
df2

B
0  3
1  4

In [129]:
df1-df2 #공통되는 컬럼 라벨이나 로우 라벨이 없는 경우는 모두 NaN값이다.

A   B
0 NaN NaN
1 NaN NaN

In [133]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
(df1,df2)

(     a    b     c     d
 0  0.0  1.0   2.0   3.0
 1  4.0  5.0   6.0   7.0
 2  8.0  9.0  10.0  11.0,
       a     b     c     d     e
 0   0.0   1.0   2.0   3.0   4.0
 1   5.0   6.0   7.0   8.0   9.0
 2  10.0  11.0  12.0  13.0  14.0
 3  15.0  16.0  17.0  18.0  19.0)

In [136]:
df2.loc[1,'b']=np.nan #특수한 값으로 지정하고 싶을 때
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [137]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [138]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [146]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [140]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [142]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [147]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [148]:
arr[0]

array([0., 1., 2., 3.])

In [149]:
arr-arr[0] #브로드캐스팅

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [151]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bde'),
                  index=['Utah','Ohio','Texas','Oregon'])
series=frame.iloc[0]
(frame,series)

(          b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0,
 b    0.0
 d    1.0
 e    2.0
 Name: Utah, dtype: float64)

In [152]:
frame-series #DataFrame과 Series 간의 산술 연산은 Series의 색인을 DataFrame의 컬럼에 맞추고 아래 로우로 전파

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [155]:
series2=pd.Series(range(3),index=['b','e','f']) 
frame+series2 #색인값을 찾을 수 없다면 그 객체는 형식을 맞추기 위해 재색인됨

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [157]:
series3=frame['d']
(frame,series3)

(          b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0,
 Utah       1.0
 Ohio       4.0
 Texas      7.0
 Oregon    10.0
 Name: d, dtype: float64)

In [158]:
frame.sub(series3,axis='index') #각 로우에 대해 연산 수행할 땐 산술 연산 메서드 사용하기

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [159]:
#6. 함수 적용과 매핑

frame=pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    0.456381 -0.512520 -0.686758
Ohio   -0.740042 -0.540136  1.208598
Texas   1.161918 -0.410277 -1.624918
Oregon -0.892202  0.085545  0.370629

In [160]:
np.abs(frame) #절댓값

b         d         e
Utah    0.456381  0.512520  0.686758
Ohio    0.740042  0.540136  1.208598
Texas   1.161918  0.410277  1.624918
Oregon  0.892202  0.085545  0.370629

In [161]:
f=lambda x: x.max()-x.min()
frame.apply(f) #apply메서드로 연산 수행 (sum과 mean같은 일반적인 통계는 DataFrame의 메서드로 사용)

b    2.054120
d    0.625681
e    2.833517
dtype: float64

In [162]:
frame.apply(f,axis='columns')

Utah      1.143139
Ohio      1.948641
Texas     2.786836
Oregon    1.262831
dtype: float64

In [164]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max']) #스칼라값을 반환할 필요 x
frame.apply(f)

b         d         e
min -0.892202 -0.540136 -1.624918
max  1.161918  0.085545  1.208598

In [166]:
format = lambda x: '%.2f' % x
frame.applymap(format) #frame객체에서 실숫값을 문자열 포맷으로 변환하고 싶다면 applymap사용

b      d      e
Utah     0.46  -0.51  -0.69
Ohio    -0.74  -0.54   1.21
Texas    1.16  -0.41  -1.62
Oregon  -0.89   0.09   0.37

In [169]:
frame['e'].map(format)

Utah      -0.69
Ohio       1.21
Texas     -1.62
Oregon     0.37
Name: e, dtype: object

In [170]:
#7. 정렬과 순위

obj=pd.Series(range(4), index=['d','a','b','c'])
obj.sort_index() #로우나 컬럼의 색인을 알파벳 순으로 정렬하려면 정렬된 새로운 객체를 반환하는 sort_index메서드 사용

a    1
b    2
c    3
d    0
dtype: int64

In [171]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
frame.sort_index() #DataFrame은 로우나 컬럼 중 하나의 축을 기준으로 정렬 가능

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [173]:
frame.sort_index(axis=1) 

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [174]:
frame.sort_index(axis=1,ascending=False) #데이터는 기본적으로 오름차순으로 정렬되며 내림차순으로 정렬 할 수 도 있음

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [176]:
obj=pd.Series([4,7,-3,2,np.nan])
obj.sort_values() #Series객체를 값에 따라 정렬하고 싶으면 sort_values() 사용, NaN값은 맨 마지막

2   -3.0
3    2.0
0    4.0
1    7.0
4    NaN
dtype: float64

In [177]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [178]:
frame.sort_values(by='b') #by옵션에 하나 이상의 컬럼 이름을 넘겨 정렬

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [179]:
frame.sort_values(by=['a','b'] ) #여러 개의 컬럼을 정렬하려면 컬럼 이름이 담긴 리스트 정렬

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [180]:
obj=pd.Series([7,-5,7,4,2,0,4])
obj.rank() #1부터 배열에 유효한 데이터 개수까지 순서를 매기는 rank메서드, 동점인 항목에 대해서는 평균 순위를 매김

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [182]:
obj.rank(method='first') #동점 항목에 대해 데이터 상에서 나타나는 순서에 따라 순위를 매길 수 있음

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [184]:
obj.rank(ascending=False,method='max') #내림차순으로, 동률인 경우 그룹 내에서 높은 순위를 적용

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [185]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [187]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [188]:
#8. 중복색인

obj=pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [189]:
obj.index.is_unique #is_unique속성은 해당 값이 유일한지 아닌지 알려준다.

False

In [190]:
obj['a'] #중복되는 색인 값이 있을 때는 스칼라 값이 아닌 하나의 Series 객체를 반환한다,

a    0
a    1
dtype: int64

In [191]:
df=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
df

0         1         2
a  1.125486  0.896593 -1.589680
a  0.763069  0.532900  1.624011
b -0.692552 -1.178095 -0.336183
b -1.163479 -1.264766  0.235868

In [192]:
df.loc['b'] #DataFrame에서 로우를 선택할 때도 마찬가지

0         1         2
b -0.692552 -1.178095 -0.336183
b -1.163479 -1.264766  0.235868

# 기술 통계 계산과 요약

In [194]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
               index=['a','b','c','d'],
               columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [197]:
df.mean(axis='columns') #pandas의 메서드는 처음부터 누락된 데이터를 제외하도록 설계되어있음

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [196]:
df.mean(axis='columns', skipna=False) #이는 skipna옵션으로 조정 가능

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [198]:
df.idxmin() #최솟값 혹은 최댓값을 가지고 있는 색인값과 같은 간접 통계를 반환

one    d
two    b
dtype: object

In [199]:
df.cumsum() #누적합

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [200]:
df.describe() #한 번에 여러개의 통계 결과를 만들어냄

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [201]:
obj=pd.Series(['a','a','b','c']*4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [203]:
obj.describe() #수치데이터가 아닐 경우 다른 요약 통계 생성

count     16
unique     3
top        a
freq       8
dtype: object

In [217]:
#1. 상관관계와 공분산: 두 쌍의 인자를 필요로 함

import pandas_datareader.data as web
all_data={ticker: web.get_data_yahoo(ticker)
         for ticker in ['AAPL','IBM','MSFT','GOOG']}

In [212]:
price=pd.DataFrame({ticker: data['Adj Close']
                   for ticker, data in all_data.items()})
price.head()

AAPL         IBM       MSFT        GOOG
Date                                                    
2016-02-08  22.125422  103.186661  45.088188  682.739990
2016-02-09  22.120768  100.821930  44.969563  678.109985
2016-02-10  21.953094   97.668968  45.361958  684.119995
2016-02-11  21.820358   95.767433  45.343704  683.109985
2016-02-12  21.887894   98.359695  46.082863  682.400024

In [213]:
volume=pd.DataFrame({ticker:data['Volume']
                    for ticker, data in all_data.items()})
volume.head()

AAPL        IBM        MSFT     GOOG
Date                                                   
2016-02-08  216085600.0  7364000.0  59290500.0  4247400
2016-02-09  177324800.0  5957200.0  46740500.0  3608900
2016-02-10  169374400.0  6469100.0  38237000.0  2638000
2016-02-11  200298800.0  7307600.0  48878600.0  3024000
2016-02-12  161405600.0  4936500.0  34243300.0  2141400

In [214]:
returns=price.pct_change() #각 주식의 퍼센트 변화율
returns.tail() 

AAPL       IBM      MSFT      GOOG
Date                                              
2021-01-29 -0.037421 -0.008078 -0.029172 -0.014690
2021-02-01  0.016520  0.012006  0.033152  0.035740
2021-02-02  0.006337 -0.009126 -0.000584  0.013759
2021-02-03 -0.007778 -0.002679  0.014571  0.073961
2021-02-04  0.012767  0.008899 -0.002798 -0.008942

In [215]:
returns['MSFT'].corr(returns['IBM']) #corr메서드는 NA가 아니며 정렬된 색인에서 연속하는 두 Series에 대해 상관관계 계산

0.5406906978071894

In [216]:
returns['MSFT'].cov(returns['IBM']) #cov메서드는 공분산 계산

0.00015455384077783183

In [218]:
returns.MSFT.corr(returns.IBM) #좀 더 편리한 문법으로 해당 컬럼을 선택할 수 있음

0.5406906978071894

In [219]:
returns.corr() #DataFrame에서 corr메서드와 cov메서드는 DataFrame 행렬에서 상관관계와 공분산을 계산

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.454222  0.709825  0.651241
IBM   0.454222  1.000000  0.540691  0.505655
MSFT  0.709825  0.540691  1.000000  0.778460
GOOG  0.651241  0.505655  0.778460  1.000000

In [221]:
returns.corrwith(returns.IBM) #corrwith 메서드는 다른 Series나 DataFrame과의 상관관계 계산

AAPL    0.454222
IBM     1.000000
MSFT    0.540691
GOOG    0.505655
dtype: float64

In [222]:
returns.corrwith(volume) #DataFrame을 넘기면 맞아떨어지는 컬럼 이름에 대한 상관관계 계산

AAPL   -0.072085
IBM    -0.112388
MSFT   -0.085034
GOOG   -0.133810
dtype: float64

In [223]:
#2. 유일값, 값 세기, 멤버십

obj=pd.Series(['c','a','d','a','a','a','b','b','c','c'])
uniques=obj.unique() #unique메서드는 중복되는 값을 제거하고 유일값만 담고 있는 Series 반환, unique.sort()를 통해 정렬 가능
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [224]:
obj.value_counts() #value_counts메서드는 Series에서 도수(frequency)를 계산하여 반환

a    4
c    3
b    2
d    1
dtype: int64

In [226]:
pd.value_counts(obj.values, sort=False) #기본으로 내림차순으로 정렬하기때문에

b    2
d    1
a    4
c    3
dtype: int64

In [227]:
obj

0    c
1    a
2    d
3    a
4    a
5    a
6    b
7    b
8    c
9    c
dtype: object

In [228]:
mask=obj.isin(['b','c']) #isin메서드는 어떤 값이 Series에 존재하는지 나타내는 불리언 벡터를 반환
mask

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool

In [229]:
obj[mask] #값을 골라내고 싶을 때 유용

0    c
6    b
7    b
8    c
9    c
dtype: object

In [230]:
to_match=pd.Series(['c','a','b','b','c','a'])
unique_vals=pd.Series(['c','b','a'])
pd.Index(unique_vals).get_indexer(to_match)
#Index.get_indexer메서드는 여러 값이 들어 있는 배열에서 유일한 값의 색인 배열을 구할 수 있음

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [231]:
data=pd.DataFrame({'Qu1':[1,3,4,3,4],
                 'Qu2':[2,3,1,2,3],
                  'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [233]:
result = data.apply(pd.value_counts).fillna(0) #apply함수에 pandas.value_counts를 넘기면
result #로우 라벨은 전체 컬럼의 유일값들을 담고 있고, 각 값은 각 컬럼에서 해당 값이 몇 번 출현했는지 나타냄

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0